@startuml

class Lexemes {
    -std::vector<std::string> lexeme; //词素使用STL vector容器模拟字符串表
    +Lexemes() = default;//Constructor
    +~Lexemes() = default;//Destructor
    +std::vector<std::string>::size_type saveLexeme(const std::string &lexemeString);//向字符串表中存储词素并返回词素在动态数组的下标
    +std::string getLexemeByIndex(int index);//取出某个下标的词素
    +int findLexeme(const std::string &lexemeTemp);//返回某个词素的下标，不存在则返回-2（-1为头节点词素）
    +void printLexemes();//打印字符串表
    +void outputLexemes(std::ofstream &file) const;//导出字符串表
}

@enduml